global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'model-api'
    static_configs:
      - targets: ['model-api:8000']
    metrics_path: '/metrics'

  - job_name: 'monitoring'
    static_configs:
      - targets: ['monitoring:8001']
    metrics_path: '/metrics'