# ---------------------------------------------------------------------------------
# Base Image for Evaluation Stage
# ---------------------------------------------------------------------------------
FROM ghcr.io/aai540-group3/pipeline-base:latest

RUN pip install \
    --no-cache-dir \
    pandas \
    numpy \
    scikit-learn \
    matplotlib \
    seaborn

ENTRYPOINT ["python"]