# ---------------------------------------------------------------------------------
# Base Image for Infrastruct Stage
# ---------------------------------------------------------------------------------
FROM ghcr.io/aai540-group3/pipeline-base:latest

RUN pip install \
    --no-cache-dir \
    boto3

ENTRYPOINT ["python"]