# ---------------------------------------------------------------------------------
# Base Image for Deployment Stage
# ---------------------------------------------------------------------------------
FROM ghcr.io/aai540-group3/pipeline-base:latest

RUN pip install \
    --no-cache-dir \
    huggingface-hub \
    loguru \
    omegaconf \
    pandas \
    scikit-learn \
    tensorflow \
    tf2onnx

ENTRYPOINT ["python"]