# ---------------------------------------------------------------------------------
# Base Image for Register Stage
# ---------------------------------------------------------------------------------
FROM ghcr.io/aai540-group3/pipeline-base:latest

RUN pip install \
    --no-cache-dir \
    mlflow \
    boto3 \
    pandas

ENTRYPOINT ["python"]