# ---------------------------------------------------------------------------------
# Base Image for Ingest Stage
# ---------------------------------------------------------------------------------
FROM ghcr.io/aai540-group3/pipeline-base:latest

RUN pip install \
    --no-cache-dir \
    boto3 \
    "numpy==1.26.0" \
    pandas \
    pyarrow \
    requests \
    tensorflow \
    tensorflow-cpu \
    ucimlrepo

ENTRYPOINT ["python"]