# ---------------------------------------------------------------------------------
# Base Image for AutoGluon Stage
# ---------------------------------------------------------------------------------
FROM ghcr.io/aai540-group3/pipeline-base:latest AS pipeline-autogluon

RUN pip install --no-cache-dir \
    autogluon.tabular \
    pandas \
    numpy \
    scikit-learn \
    joblib \
    optuna \
    shap \
    plotly \
    kaleido \
    category_encoders

ENTRYPOINT ["python"]