model_name: autogluon
metrics_output_path: /home/user/project/pipeline-opensource/models/autogluon/artifacts/metrics.json
test_data_path: 
  /home/user/project/pipeline-opensource/models/autogluon/artifacts/preprocessed_test_data.csv
evaluation_date: '2024-10-19T08:49:46.480079'
dataset_version: v1.0
