engines:
  bandit:
    enabled: true
  duplication:
    enabled: false
  eslint:
    enabled: false
  flake8:
    enabled: true
  jacksonlint:
    enabled: false
  mypy:
    enabled: true
  pydocstyle:
    enabled: true
  pylint:
    enabled: true
  scalastyle:
    enabled: false

files:
  include:
    - "src/**"
    - "scripts/**"
    - "configs/**"
  exclude:
    - "tests/**"
    - "docs/**"
    - ".venv/**"
    - "data/**"
    - "models/**"
    - "notebooks/**"
    - ".ipynb_checkpoints/**"
    - "**/__pycache__/**"
    - "*.egg-info/**"
    - "*.egg/**"

tools:
  flake8:
    config: .flake8
  pylint:
    config: .pylintrc
  mypy:
    config: mypy.ini

ignore:
  - "**/migrations/**"
  - "**/settings.py"
