---
engines:
  bandit:
    enabled: true
  duplication:
    enabled: false
  eslint-8:
    enabled: false
  flake8:
    enabled: true
  jacksonlinter:
    enabled: false
  markdownlint:
    enabled: true
  metrics:
    enabled: false
  mypy:
    enabled: true
  pmdcpd:
    enabled: false
  pylintpython3:
    enabled: true
  trivy:
    enabled: true

exclude_paths:
  - "tests/**"
  - "docs/**"
  - ".venv/**"
  - "data/**"
  - "models/**"
  - "notebooks/**"
  - ".ipynb_checkpoints/**"
  - "**/__pycache__/**"
  - "*.egg-info/**"
  - "*.egg/**"
  - "**/migrations/**"
  - "**/settings.py"

tools:
  flake8:
    config: .flake8
  pylintpython3:
    config: .pylintrc
  mypy:
    config: mypy.ini
