---
engines:
  duplication:
    enabled: false
    minTokenMatch: 20
    skipLexicalErrors: false
    ignoreLiterals: false
    ignoreIdentifiers: true
    ignoreAnnotations: false
    ignoreUsings: false
  ameba:
    enabled: false
  bandit:
    enabled: false
  brakeman:
    enabled: false
  checkov:
    enabled: false
  checkstyle:
    enabled: false
  codacy-scalameta-pro:
    enabled: false
  codenarc:
    enabled: false
  coffeelint:
    enabled: false
  cppcheck:
    enabled: false
  credo:
    enabled: false
  dartanalyzer:
    enabled: false
  detekt:
    enabled: false
  eslint-8:
    enabled: false
  flawfinder:
    enabled: false
  hadolint:
    enabled: false
  jacksonlinter:
    enabled: false
  markdownlint:
    enabled: false
  phpcs:
    enabled: false
  phpmd:
    enabled: false
  pmd:
    enabled: false
  pmdcpd:
    enabled: false
  prospector:
    enabled: false
  psscriptanalyzer:
    enabled: false
  pylintpython3:
    enabled: true
  remark-lint:
    enabled: false
  revive:
    enabled: false
  rubocop:
    enabled: false
  scalastyle:
    enabled: false
  semgrep:
    enabled: false
  shellcheck:
    enabled: false
  sonarcsharp:
    enabled: false
  sonarvb:
    enabled: false
  spectral:
    enabled: false
  SQLint:
    enabled: false
  stylelint:
    enabled: false
  swiftlint:
    enabled: false
  trivy:
    enabled: false
  tsqllint:
    enabled: false

exclude_paths:
  - ".devcontainer/**"
  - ".dvc/**"
  - ".git/**"
  - ".gitea/**"
  - ".github/**"
  - ".ipynb_checkpoints/**"
  - ".temp/**"
  - ".venv/**"
  - ".vscode/**"
  - "*.egg-info"
  - "*.egg"
  - "**/__pycache__/**"
  - "**/migrations/**"
  - "**/settings.py"
  - "data/**"
  - "debug/**"
  - "docs/**"
  - "huggingface/**"
  - "models/**"
  - "node_modules/**"
  - "notebooks/**"
  - "outputs/**"
  - "temp/**"
  - "terraform/**"
  - "tests/**"
  - "video-assets/**"

languages:
  python:
    enabled: true
  javascript:
    enabled: false
  typescript:
    enabled: false
