stages:
  ingest:
    cmd: python src/data/ingestion.py hydra.run.dir=.
    deps:
      - src/data/ingestion.py
    outs:
      - data/raw/:
          remote: datasets_remote

  clean:
    cmd: python src/data/cleaning.py hydra.run.dir=.
    deps:
      - src/data/cleaning.py
      - data/raw/
    outs:
      - data/interim/:
          remote: datasets_remote

  split:
    cmd: python src/data/splitting.py hydra.run.dir=.
    deps:
      - src/data/splitting.py
      - data/interim/data.csv
    outs:
      - data/processed/train.csv:
          remote: datasets_remote
      - data/processed/test.csv:
          remote: datasets_remote

  train:
    cmd: python src/models/model1/train.py hydra.run.dir=.
    deps:
      - src/models/model1/train.py
      - data/processed/train.csv
    outs:
      - models/trained_model.joblib:
          remote: models_remote
      - dvclive/:
          cache: false

  evaluate:
    cmd: python src/visualization/evaluation.py hydra.run.dir=.
    deps:
      - src/visualization/evaluation.py
      - models/trained_model.joblib
      - data/processed/test.csv
    metrics:
      - reports/metrics.json

metrics:
  - dvclive/metrics.json
plots:
  - dvclive/plots/metrics:
      x: step
