train:
  enabled: true
  cache: true

  data:
    train_path: ${paths.processed}/train_features.parquet
    val_path: ${paths.processed}/val_features.parquet
    test_path: ${paths.processed}/test_features.parquet

  model:
    name: ${model.name}
    save_path: ${paths.models}/${model.name}/model.pkl

  metrics:
    path: ${paths.metrics}/training/${model.name}
    save_best: true

  artifacts:
    path: ${paths.models}/${model.name}/artifacts
    save:
      - model
      - scaler
      - feature_names