model_name: autogluon
metrics_output_path: /home/user/project/reports/metrics/autogluon_metrics.json
test_data_path: /home/user/project/data/processed/test.csv
evaluation_date: '2024-09-22T18:59:26.869446'
dataset_version: v1.0
