data_hash: 475f08bb1147cc6ead6a4cd0a62a4ea3
n_samples: 100121
n_features: 95
class_distribution_before_smote:
  '0': 88764
  '1': 11357
imbalance_ratio_before_smote: 7.815796425112265
class_distribution_after_smote:
  '1': 53257
  '0': 53257
imbalance_ratio_after_smote: 1.0
train_size: 60072
val_size: 20024
test_size: 20025
train_size_after_smote: 106514
