stages:
  setup:
    cmd:
      - python3 -m virtualenv .venv
      - . .venv/bin/activate
      - pip install uv
      - uv pip install -r requirements.txt
      - pip freeze > requirements-frozen.txt
      - .venv/bin/python src/utils.py patch_nvidia_gpu
    deps:
      - requirements.txt
      - src/utils.py
    outs:
      - requirements-frozen.txt

  infrastruct:
    cmd: .venv/bin/python src/infrastruct.py
    deps:
      - src/infrastruct.py
      - requirements-frozen.txt

  ingest:
    cmd: .venv/bin/python src/ingest.py
    deps:
      - src/ingest.py
      - requirements-frozen.txt
    outs:
      - data/raw/data.csv
      - data/raw/data.parquet
      - data/raw/metadata.json
      - data/raw/variables.json

  preprocess:
    cmd: .venv/bin/python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/data.csv
      - requirements-frozen.txt
    outs:
      - data/interim/data_cleaned.parquet

  explore:
    cmd: .venv/bin/python src/explore.py
    deps:
      - src/explore.py
      - data/raw/data.csv
      - data/interim/data_cleaned.parquet
      - requirements-frozen.txt
    outs:
      - reports/plots/readmitted_distribution.png:
          cache: false
      - reports/plots/time_in_hospital_vs_readmission.png:
          cache: false
      - reports/plots/age_vs_readmission.png:
          cache: false
      - reports/plots/service_utilization_vs_readmission.png:
          cache: false
      - reports/plots/correlation_matrix.png:
          cache: false
    metrics:
      - reports/cleanlab/detailed_analysis.txt:
          cache: false
      - reports/cleanlab/problematic_cases.csv:
          cache: false
      - reports/cleanlab/feature_importance.csv:
          cache: false
    plots:
      - reports/cleanlab/cleanlab_confidence_distribution.png:
          cache: false
      - reports/cleanlab/cleanlab_confusion_matrix.png:
          cache: false

  featurize:
    cmd: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python .venv/bin/python src/featurize.py
    deps:
      - src/featurize.py
      - data/interim/data_cleaned.parquet
      - feature_store.yaml
      - requirements-frozen.txt
    outs:
      - data/interim/data_featured.parquet

  train_logistic_regression:
    cmd: .venv/bin/python models/logistic_regression/model.py
    deps:
      - models/logistic_regression/model.py
      - data/interim/data_featured.parquet
      - requirements-frozen.txt
    outs:
      - models/logistic_regression/artifacts/model/model.joblib:
          cache: true
      - models/logistic_regression/artifacts/model/model_summary.txt:
          cache: true
      - models/logistic_regression/artifacts/model/scaler.joblib:
          cache: true
    metrics:
      - models/logistic_regression/artifacts/metrics/metrics.json:
          cache: false
      - models/logistic_regression/artifacts/metrics/feature_importance.csv:
          cache: false
    plots:
      - models/logistic_regression/artifacts/plots/confusion_matrix.png:
          cache: false
      - models/logistic_regression/artifacts/plots/roc_curve.png:
          cache: false
      - models/logistic_regression/artifacts/plots/feature_importance.png:
          cache: false

  train_neural_network:
    cmd: .venv/bin/python models/neural_network/model.py
    deps:
      - models/neural_network/model.py
      - data/interim/data_featured.parquet
      - requirements-frozen.txt
    outs:
      - models/neural_network/artifacts/model/model.h5:
          cache: true
      - models/neural_network/artifacts/model/model_summary.txt:
          cache: true
      - models/neural_network/artifacts/model/scaler.joblib:
          cache: true
    metrics:
      - models/neural_network/artifacts/metrics/metrics.json:
          cache: false
      - models/neural_network/artifacts/metrics/history.json:
          cache: false
    plots:
      - models/neural_network/artifacts/plots/confusion_matrix.png:
          cache: false
      - models/neural_network/artifacts/plots/roc_curve.png:
          cache: false
      - models/neural_network/artifacts/plots/model_architecture.png:
          cache: false

  train_autogluon:
    cmd: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python .venv/bin/python models/autogluon/model.py
    deps:
      - models/autogluon/model.py
      - data/interim/data_featured.parquet
      - requirements-frozen.txt
    outs:
      - models/autogluon/artifacts/model/model_info.txt:
          cache: true
      - models/autogluon/artifacts/model/best_model_architecture.txt:
          cache: true
      - models/autogluon/artifacts/model/leaderboard.csv:
          cache: true
      - models/autogluon/artifacts/model/feature_importance.csv:
          cache: true
      - models/autogluon/artifacts/plots/best_model_architecture.png:
          cache: false
    metrics:
      - models/autogluon/artifacts/metrics/metrics.json:
          cache: false
      - models/autogluon/artifacts/metrics/feature_importance.json:
          cache: false
    plots:
      - models/autogluon/artifacts/plots/confusion_matrix.png:
          cache: false
      - models/autogluon/artifacts/plots/roc_curve.png:
          cache: false
      - models/autogluon/artifacts/plots/feature_importance.png:
          cache: false
      - models/autogluon/artifacts/plots/model_feature_importance.png:
          cache: false

  visualize:
    cmd: .venv/bin/python src/visualize.py
    deps:
      - src/visualize.py
      - models/autogluon/artifacts/metrics/metrics.json
      - models/logistic_regression/artifacts/metrics/metrics.json
      - models/neural_network/artifacts/metrics/metrics.json
      - data/processed/test.parquet
      - requirements-frozen.txt
    outs:
      - reports/figures/model_comparison.png:
          cache: false
      - models/autogluon/artifacts/plots/shap_force_plot.png:
          cache: false
      - models/autogluon/artifacts/plots/shap_summary.png:
          cache: false
      - models/autogluon/artifacts/plots/shap_importance.png:
          cache: false
      - models/logistic_regression/artifacts/plots/shap_force_plot.png:
          cache: false
      - models/logistic_regression/artifacts/plots/shap_summary.png:
          cache: false
      - models/logistic_regression/artifacts/plots/shap_importance.png:
          cache: false
      - models/neural_network/artifacts/plots/shap_force_plot.png:
          cache: false
      - models/neural_network/artifacts/plots/shap_summary.png:
          cache: false
      - models/neural_network/artifacts/plots/shap_importance.png:
          cache: false
