stages:
  setup:
    cmd:
      # CREATE VIRTUAL ENVIRONMENTS FOR EACH STAGE
      - uv venv .venv-infrastruct --python 3.10
      - . .venv-infrastruct/bin/activate && uv pip install -r requirements-infrastruct.txt
      - uv venv .venv-ingest --python 3.10
      - . .venv-ingest/bin/activate && uv pip install -r requirements-ingest.txt
      - uv venv .venv-preprocess --python 3.10
      - . .venv-preprocess/bin/activate && uv pip install -r requirements-preprocess.txt
      - uv venv .venv-explore --python 3.10
      - . .venv-explore/bin/activate && uv pip install -r requirements-explore.txt
      - uv venv .venv-featurize --python 3.11
      - . .venv-featurize/bin/activate && uv pip install -r requirements-featurize.txt
      - uv venv .venv-autogluon --python 3.10
      - . .venv-autogluon/bin/activate && uv pip install -r requirements-autogluon.txt
      - uv venv .venv-logisticregression --python 3.10
      - . .venv-logisticregression/bin/activate && uv pip install -r requirements-logisticregression.txt
      - uv venv .venv-neuralnetwork --python 3.10
      - . .venv-neuralnetwork/bin/activate && uv pip install -r requirements-neuralnetwork.txt
      - uv venv .venv-deploy --python 3.10
      - . .venv-deploy/bin/activate && uv pip install -r requirements-deploy.txt
      # INFRASTRUCT
      - . .venv-infrastruct/bin/activate && python src/infrastruct.py
    outs:
      - .venv-infrastruct
      - .venv-ingest
      - .venv-preprocess
      - .venv-explore
      - .venv-featurize
      - .venv-autogluon
      - .venv-logisticregression
      - .venv-neuralnetwork
      - .venv-deploy

  ingest:
    cmd:
      - . .venv-ingest/bin/activate && python src/ingest.py
    deps:
      - .venv-ingest
      - src/ingest.py
    outs:
      - data/raw/data.csv
      - data/raw/metadata.json
      - data/raw/variables.json
      - data/raw/data.parquet

  preprocess:
    cmd:
      - . .venv-preprocess/bin/activate && python src/preprocess.py
    deps:
      - .venv-preprocess
      - src/preprocess.py
      - data/raw/data.csv
    outs:
      - data/interim/data_cleaned.parquet
      - data/interim/feature_names.joblib

  explore:
    cmd:
      - . .venv-explore/bin/activate && python src/explore.py
      - . .venv-explore/bin/activate && dvc dag --md > reports/figures/dag.md
    deps:
      - .venv-explore
      - src/explore.py
      - data/raw/data.csv
      - data/interim/data_cleaned.parquet
    outs:
      - reports/figures/dag.md
      - reports/cleanlab/detailed_analysis.txt
      - reports/cleanlab/problematic_cases.csv
      - reports/cleanlab/feature_importance.csv
    plots:
      - reports/plots/readmitted_distribution.png
      - reports/plots/time_in_hospital_vs_readmission.png
      - reports/plots/age_vs_readmission.png
      - reports/plots/service_utilization_vs_readmission.png
      - reports/plots/correlation_matrix.png
      - reports/cleanlab/cleanlab_confusion_matrix.png
      - reports/cleanlab/cleanlab_confidence_distribution.png

  featurize:
    cmd:
      - . .venv-featurize/bin/activate && python src/featurize.py
    deps:
      - .venv-featurize
      - src/featurize.py
      - data/interim/data_cleaned.parquet
      - feature_store.yaml
    outs:
      - requirements-featurize-frozen.txt
      - data/interim/data_featured.parquet

  train_autogluon:
    cmd:
      - . .venv-autogluon/bin/activate && python src/utils.py patch_nvidia_gpu
      - . .venv-autogluon/bin/activate && PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python python models/autogluon/model.py
    deps:
      - src/utils.py
      - models/autogluon/model.py
      - .venv-train_autogluon
      - data/interim/data_featured.parquet
    outs:
      - models/autogluon/artifacts/model
    metrics:
      - models/autogluon/artifacts/metrics/metrics.json
    plots:
      - models/autogluon/artifacts/plots/confusion_matrix.png
      - models/autogluon/artifacts/plots/feature_importance.png
      - models/autogluon/artifacts/plots/roc_curve.png

  train_logisticregression:
    cmd:
      - . .venv-logisticregression/bin/activate && python models/logistic_regression/model.py
    deps:
      - .venv-logisticregression
      - models/logistic_regression/model.py
      - data/interim/data_featured.parquet
    outs:
      - models/logistic_regression/artifacts/model
    metrics:
      - models/logistic_regression/artifacts/metrics/metrics.json
    plots:
      - models/logistic_regression/artifacts/plots/confusion_matrix.png
      - models/logistic_regression/artifacts/plots/roc_curve.png

  train_neuralnetwork:
    cmd:
      - . .venv-neuralnetwork/bin/activate && python models/neural_network/model.py
    deps:
      - .venv-neuralnetwork
      - models/neural_network/model.py
      - data/interim/data_featured.parquet
    outs:
      - models/neural_network/artifacts/model
    metrics:
      - models/neural_network/artifacts/metrics/metrics.json
    plots:
      - models/neural_network/artifacts/plots/confusion_matrix.png
      - models/neural_network/artifacts/plots/model_architecture.png
      - models/neural_network/artifacts/plots/roc_curve.png

  deploy:
    cmd:
      - . .venv-deploy/bin/activate && python src/deploy.py
    deps:
      - .venv-deploy
      # PLOTS
      - models/autogluon/artifacts/model/feature_importance.csv
      # MODELS
      - models/autogluon/artifacts/model/predictor.pkl
      - models/logistic_regression/artifacts/model/model.joblib
      - models/neural_network/artifacts/model/model.keras
      # METRICS
      - models/autogluon/artifacts/metrics/metrics.json
      - models/logistic_regression/artifacts/metrics/metrics.json
      - models/neural_network/artifacts/metrics/metrics.json

artifacts:
  diabetes-dataset:
    path: data/raw/data.csv
    type: dataset
    desc: "Diabetes 130-US hospitals for years 1999-2008 dataset"
    labels:
      - tabular
      - healthcare
    meta:
      source: "UCI Machine Learning Repository"
      url: https://archive.ics.uci.edu/ml/datasets/diabetes+130-us+hospitals+for+years+1999-2008
      records: 101766
      features: 55
  logistic_regression:
    path: models/logistic_regression/artifacts/model/model.joblib
    type: model
    desc: "Trained Logistic Regression model for readmission prediction"
    labels:
      - baseline
      - interpretable
    meta:
      features: "engineered features, standardized"
      algorithm: sklearn.linear_model.LogisticRegression
  neural_network:
    path: models/neural_network/artifacts/model/model.keras
    type: model
    desc: "Trained deep Neural Network model for readmission prediction"
    labels:
      - deep-learning
      - tensorflow
    meta:
      architecture: "MLP, 3 hidden layers"
      optimizer: Adam
      epochs: 100
  autogluon:
    path: models/autogluon/artifacts/model/model.pkl
    type: model
    desc: "Trained AutoGluon ensemble model for readmission prediction"
    labels:
      - automl
      - ensemble
    meta:
      framework: autogluon
      hyperparameters: "tuned with best_quality preset"