stages:
  infrastruct:
    cmd: >-
      UV_LINK_MODE=copy
      pipx run
      uv run
      --python 3.11
      --with boto3
      --with loguru
      --with omegaconf
      --with pandas
      python pipeline infrastruct
    deps:
      - pipeline/__init__.py
      - pipeline/__main__.py
      - pipeline/stages/infrastruct.py
      - pipeline/stages/stage.py
      - requirements/base.txt
    metrics:
      - metrics/infrastruct:
          cache: true

  ingest:
    cmd: >-
      UV_LINK_MODE=copy
      pipx run
      uv run
      --python 3.11
      --with loguru
      --with matplotlib
      --with omegaconf
      --with pandas
      --with pyarrow
      --with seaborn
      --with ucimlrepo
      python pipeline ingest
    deps:
      - metrics/infrastruct/metrics.json
      - pipeline/__init__.py
      - pipeline/__main__.py
      - pipeline/stages/ingest.py
      - pipeline/stages/stage.py
    outs:
      - data/raw:
          cache: true
    metrics:
      - metrics/ingest:
          cache: true
    plots:
      - plots/ingest:
          cache: true

  preprocess:
    cmd: >-
      UV_LINK_MODE=copy
      pipx run
      uv run
      --python 3.11
      --with loguru
      --with matplotlib
      --with omegaconf
      --with pandas
      --with pyarrow
      --with seaborn
      python pipeline preprocess
    deps:
      - data/raw/data.csv
      - pipeline/__init__.py
      - pipeline/__main__.py
      - pipeline/stages/preprocess.py
      - pipeline/stages/stage.py
    outs:
      - data/interim/cleaned.parquet:
          cache: true
    metrics:
      - metrics/preprocess:
          cache: true
    plots:
      - plots/preprocess:
          cache: true

  explore:
    cmd: >-
      UV_LINK_MODE=copy
      pipx run
      uv run
      --python 3.11
      --with loguru
      --with matplotlib
      --with omegaconf
      --with pandas
      --with pyarrow
      --with scikit-learn
      --with seaborn
      python pipeline explore
    deps:
      - data/interim/cleaned.parquet
      - pipeline/__init__.py
      - pipeline/__main__.py
      - pipeline/stages/explore.py
      - pipeline/stages/stage.py
    metrics:
      - metrics/explore:
          cache: true
    plots:
      - plots/explore:
          cache: true

  featurize:
    cmd: >-
      UV_LINK_MODE=copy
      pipx run
      uv run
      --python 3.11
      --with boto3
      --with loguru
      --with matplotlib
      --with omegaconf
      --with pandas
      --with pyarrow
      --with scikit-learn
      --with seaborn
      python pipeline featurize
    deps:
      - data/interim/cleaned.parquet
      - pipeline/__init__.py
      - pipeline/__main__.py
      - pipeline/stages/featurize.py
      - pipeline/stages/stage.py
    outs:
      - data/processed/features.parquet:
          cache: true
    metrics:
      - metrics/featurize:
          cache: true
    plots:
      - plots/featurize:
          cache: true

  feast:
    cmd: >-
      UV_LINK_MODE=copy
      pipx run
      uv run
      --python 3.11
      --with dask[dataframe]
      --with docker
      --with feast[postgres]
      --with loguru
      --with matplotlib
      --with omegaconf
      --with pandas
      --with psycopg2-binary
      --with pyarrow
      --with seaborn
      --with testcontainers
      python pipeline feast
    deps:
      - data/processed/features.parquet
      - pipeline/__init__.py
      - pipeline/__main__.py
      - pipeline/stages/feast.py
      - pipeline/stages/feature_repo.py
      - pipeline/stages/stage.py
    outs:
      - feature_repo:
          cache: true
    metrics:
      - metrics/feast:
          cache: true

  autogluon:
    cmd: >-
      UV_LINK_MODE=copy
      pipx run
      uv run
      --python 3.11
      --with autogluon
      --with autogluon.tabular[light]
      --with imbalanced-learn
      --with loguru
      --with matplotlib
      --with omegaconf
      --with pandas
      --with pyarrow
      --with seaborn
      --with shap
      --with torch
      python pipeline autogluon
    deps:
      - data/processed/features.parquet
      - pipeline/__init__.py
      - pipeline/__main__.py
      - pipeline/models/autogluon.py
      - pipeline/models/metrics.py
      - pipeline/models/model.py
      - pipeline/stages/autogluon.py
      - pipeline/stages/stage.py
    outs:
      - models/autogluon:
          cache: true
    metrics:
      - metrics/autogluon:
          cache: true
    plots:
      - plots/autogluon:
          cache: true

  logisticregression:
    cmd: >-
      UV_LINK_MODE=copy
      pipx run
      uv run
      --python 3.9
      --with imbalanced-learn
      --with loguru
      --with matplotlib
      --with omegaconf
      --with pandas
      --with pyarrow
      --with seaborn
      --with shap
      --with torch
      python pipeline logisticregression
    deps:
      - data/processed/features.parquet
      - pipeline/__init__.py
      - pipeline/__main__.py
      - pipeline/models/logisticregression.py
      - pipeline/models/metrics.py
      - pipeline/models/model.py
      - pipeline/stages/logisticregression.py
      - pipeline/stages/stage.py
    outs:
      - models/logisticregression:
          cache: true
    metrics:
      - metrics/logisticregression:
          cache: true
    plots:
      - plots/logisticregression:
          cache: true

  neuralnetwork:
    cmd: >-
      UV_LINK_MODE=copy
      pipx run
      uv run
      --python 3.9
      --with imbalanced-learn
      --with loguru
      --with matplotlib
      --with omegaconf
      --with pandas
      --with pyarrow
      --with seaborn
      --with shap
      --with torch
      python pipeline neuralnetwork
    deps:
      - data/processed/features.parquet
      - pipeline/__init__.py
      - pipeline/__main__.py
      - pipeline/models/metrics.py
      - pipeline/models/model.py
      - pipeline/models/neuralnetwork.py
      - pipeline/stages/neuralnetwork.py
      - pipeline/stages/stage.py
    outs:
      - models/neuralnetwork:
          cache: true
    metrics:
      - metrics/neuralnetwork:
          cache: true
    plots:
      - plots/neuralnetwork:
          cache: true
