train_size: 77156
val_size: 9645
test_size: 9645
features: 60
data_hash: f2f8871f244f5613bab016ab86d3342f
autogluon_GBM:
  extra_trees: false
  learning_rate: 0.1
  num_boost_round: 100
  num_leaves: 16
  early_stopping_rounds: 10
