models:
  names:
    - logistic_regression
    - autogluon
    - neural_network
  output: models

data:
  raw_file: data/raw/data.csv
  interim_file: data/interim/data_cleaned.csv
  featured_file: data/processed/data_featured.csv
  train_file: data/processed/train.csv
  test_file: data/processed/test.csv
  processed: data/processed
  config_path: conf
  config_name: config

reports:
  metrics: reports/metrics

dvclive: dvclive

dataset:
  name: "aai540-group3/diabetes-readmission"
  version: "v1.0"

training:
  split:
    test_size: 0.2
    random_state: 42

feature_engineering:
  add_polynomial_features: true
  poly_degree: 2

model:
  logistic_regression:
    model_file: model.pkl
    params:
      penalty: "l2"
      C: 1.0
      solver: "lbfgs"
      max_iter: 1000
      random_state: 42

  autogluon:
    model_file: model.pkl
    params:
      presets: "best_quality"
      time_limit: 3600
      verbosity: 2
      gbm_num_boost_round: 100

  neural_network:
    model_file: model.pkl
    params:
      layers:
        - units: 64
          activation: "relu"
          dropout: 0.5
        - units: 32
          activation: "relu"
          dropout: 0.5
        - units: 32
          activation: "relu"
          dropout: 0.5
        - units: 16
          activation: "relu"
      optimizer:
        type: "adamw"
        learning_rate: 0.0001
      loss: "binary_crossentropy"
      metrics:
        - "accuracy"
      batch_size: 32
      epochs: 100
      patience: 15
