models:
  names:
    - logistic_regression
    - autogluon
  output: models

data:
  raw_file: data/raw/data.csv
  interim_file: data/interim/data_cleaned.csv
  featured_file: data/processed/data_featured.csv
  train_file: data/processed/train.csv
  test_file: data/processed/test.csv
  processed: data/processed
  config_path: conf
  config_name: config

reports:
  metrics: reports/metrics

dvclive: dvclive

dataset:
  name: "aai540-group3/diabetes-readmission"
  version: "v1.0"

training:
  split:
    test_size: 0.2
    random_state: 42

feature_engineering:
  add_polynomial_features: true
  poly_degree: 2

model:
  logistic_regression:
    params:
      penalty: "l2"
      C: 1.0
      solver: "lbfgs"
      max_iter: 1000
      random_state: 42

  autogluon:
    params:
      presets: "best_quality"
      time_limit: 3600
      verbosity: 2
      gbm_num_boost_round: 100
