model_name: autogluon
metrics_output_path: /home/user/project/pipeline-opensource/reports/metrics/autogluon_metrics.json
test_data_path: /home/user/project/pipeline-opensource/data/processed/test.csv
evaluation_date: '2024-10-19T05:31:20.426533'
dataset_version: v1.0
