model_name: neural_network
metrics_output_path: 
  /home/user/project/pipeline-opensource/models/neural_network/artifacts/metrics.json
evaluation_date: '2024-10-19T16:36:50.937067'
dataset_version: v1.0
