name: autogluon
type: autogluon
framework: autogluon

model:
  label: ${data.target_column}
  problem_type: binary
  eval_metric: roc_auc
  verbosity: 2

training:
  time_limit: 3600
  presets: best_quality
  hyperparameters:
    GBM:
      num_boost_round: 1000
      learning_rate: 0.05
      num_leaves: 31
      feature_fraction: 0.8
      bagging_fraction: 0.8
      bagging_freq: 5
      min_child_samples: 20
    NN:
      num_epochs: 100
      learning_rate: 0.001
      dropout_prob: 0.1
      hidden_units: [128, 64]
      activation: relu
    RF:
      n_estimators: 300
      max_depth: 10
      min_samples_leaf: 3
      class_weight: balanced
  hyperparameter_tune_kwargs:
    num_trials: 100
    scheduler: local
    searcher: random
    max_concurrent_trials: 4

quick_mode:
  training:
    time_limit: 60
    presets: medium_quality_faster_train
    hyperparameters:
      GBM:
        num_boost_round: 10
      NN:
        num_epochs: 1
      RF:
        n_estimators: 10
    hyperparameter_tune_kwargs: null
