name: neural
type: neural_network
framework: tensorflow

architecture:
  input_layer:
    dropout: 0.1
    batch_norm: true
  hidden_layers:
    - units: 128
      activation: relu
      dropout: 0.3
      batch_norm: true
    - units: 64
      activation: relu
      dropout: 0.2
      batch_norm: true
    - units: 32
      activation: relu
      dropout: 0.1
      batch_norm: true
  output_layer:
    activation: sigmoid
    units: 1

training:
  optimizer:
    name: adam
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
    epsilon: 1e-07
  loss: binary_crossentropy
  metrics:
    - accuracy
    - auc
    - precision
    - recall
  batch_size: 256
  epochs: 100
  early_stopping:
    monitor: val_loss
    patience: 10
    min_delta: 0.001
    restore_best_weights: true
  model_checkpoint:
    monitor: val_loss
    save_best_only: true
  class_weight: balanced

quick_mode:
  architecture:
    hidden_layers:
      - units: 16
        activation: relu
        dropout: 0.0
        batch_norm: false
  training:
    optimizer:
      learning_rate: 0.01
    batch_size: 128
    epochs: 1
    early_stopping: null
    model_checkpoint: null
