api:
  host: 0.0.0.0
  port: 8000
  workers: 4
  timeout: 30
  cors:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]

  endpoints:
    predict:
      batch_size: 32
      timeout: 10

    monitoring:
      enabled: true
      metrics:
        - latency
        - throughput
        - error_rate

    authentication:
      enabled: true
      type: api_key
      header_name: X-API-Key