defaults:
  - _self_
  - infrastructure: aws
  - experiment: base
  - model: base
  - tracking: mlflow
  - pipeline: default
  - monitoring: default
  - features: store
  - data: preprocessing
  - deploy: default
  - api: fastapi
  - environment: prod
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Version information
version: 1.0.0
debug: ${oc.env:DEBUG,false}

# Experiment tracking configuration
tracking:
  mlflow:
    enabled: true
    tracking_uri: ${oc.env:MLFLOW_TRACKING_URI}
    registry_uri: ${oc.env:MLFLOW_REGISTRY_URI}
    experiment_name: ${experiment.name}
    tags: []
    log_artifacts: true
    log_code: true

  wandb:
    enabled: true
    project: ${experiment.name}
    entity: ${oc.env:WANDB_ENTITY}
    tags: []
    log_artifacts: true
    log_code: true

# Path configuration
paths:
  root: ${hydra:runtime.cwd}
  data: ${paths.root}/data
  raw: ${paths.data}/raw
  interim: ${paths.data}/interim
  processed: ${paths.data}/processed
  features: ${paths.data}/features
  models: ${paths.root}/models
  metrics: ${paths.root}/metrics
  infrastructure: ${paths.root}/infrastructure
  monitoring: ${paths.root}/monitoring
  registry: ${paths.root}/registry
  deploy: ${paths.root}/deploy
  reports: ${paths.root}/reports

# AWS configuration
aws:
  region: ${oc.env:AWS_REGION,us-east-1}
  profile: ${oc.env:AWS_PROFILE,default}
  bucket: ${oc.env:BUCKET_NAME}
  prefix: ${experiment.name}
