aws:
  enabled: true
  region: ${oc.env:AWS_REGION,us-east-1}
  profile: ${oc.env:AWS_PROFILE,default}

  # IAM Configuration
  iam:
    group:
      name: ${oc.env:GROUP_NAME}
      policies:
        - AWSLambdaFullAccess
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - CloudWatchFullAccess

    users:
      emails: ${oc.env:EMAILS}
      initial_password: ${oc.env:INITIAL_PASSWORD}
      require_mfa: true
      create_access_keys: true

  # S3 Configuration
  s3:
    bucket:
      name: ${oc.env:BUCKET_NAME}
      keys: ${oc.env:BUCKET_KEYS}
    versioning: enabled
    encryption: AES256
    public_access_block: true
    lifecycle_rules:
      - enabled: true
        prefix: logs/
        expiration_days: 90
      - enabled: true
        prefix: temp/
        expiration_days: 1

  # DynamoDB Configuration
  dynamodb:
    table:
      name: ${oc.env:TABLE_NAME}
      hash_key: id
      attributes:
        - name: id
          type: S
      billing_mode: PAY_PER_REQUEST
      ttl:
        enabled: true
        attribute_name: expiration_time

  # Budget Configuration
  budgets:
    - name: MonthlyBudget
      amount: 10
      currency: USD
      time_unit: MONTHLY
      alerts:
        - threshold: 80
          type: ACTUAL
          subscribers: ${oc.env:EMAILS}

  # Monitoring Configuration
  monitoring:
    enabled: true
    namespace: aai540-group3
    metrics:
      - name: ModelLatency
        unit: Milliseconds
      - name: PredictionCount
        unit: Count
      - name: ErrorRate
        unit: Percent
    alarms:
      - name: HighErrorRate
        metric_name: ErrorRate
        threshold: 5
        period: 300
        evaluation_periods: 2
        comparison_operator: GreaterThanThreshold
        actions_enabled: true

  # SNS Configuration
  sns:
    topics:
      - name: alerts
        display_name: ML Pipeline Alerts
        subscriptions: ${oc.env:EMAILS}
