name: AWS Nuke

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0


      # NOTE: NOT READY TO BE TESTED
      # - name: Run AWS Actions
      #   uses: drengskapur/aws-actions@v1
