name: CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run DVC pipeline
      run: |
        dvc pull
        dvc repro

    - name: Deploy to HuggingFace
      if: startsWith(github.ref, 'refs/tags/')
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python src/stages/deploy.py

  release:
    needs: deploy
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          models/*/model.pkl
          metrics/evaluation/model_comparison.json
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
