name: "Deploy HF Space: OpenAI TTS"

on:
  workflow_dispatch:
  push:
    paths:
      - 'huggingface/openai-tts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Inputs
        run: |
          set -e
          if [ -z "${{ secrets.HUGGINGFACE_TOKEN }}" ]; then
            echo "Error: HUGGINGFACE_TOKEN is not set."
            exit 1
          fi
          if [ -z "${{ secrets.HF_USERNAME }}" ]; then
            echo "Error: HF_USERNAME is not set."
            exit 1
          fi
          if [ -z "${{ secrets.HF_SPACE }}" ]; then
            echo "Error: HF_SPACE is not set."
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        with:
          fetch-depth: 1

      - name: Install Hugging Face CLI
        run: pip install -U "huggingface_hub[cli]"

      - name: Login to Hugging Face
        run: huggingface-cli login --token "${{ secrets.HUGGINGFACE_TOKEN }}"

      - name: Upload Files to Hugging Face Space
        run: |
          huggingface-cli upload "${{ secrets.HF_USERNAME }}/${{ secrets.HF_SPACE }}" \
            ./huggingface/openai-tts/ . \
            --include-untracked --yes --recursive
