name: Deploy HF TTS Space

on:
  push:
    branches:
      - main
    paths:
      - "pipeline/huggingface/spaces/openai-tts/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HF_TRANSFER_ENABLED: "1"
      REPO_ID: aai540-group3/openai-tts
      REMOTE_DIR: "."
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache Apt Packages
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: |
            /var/cache/apt/archives/*.deb
            /var/lib/apt/lists/*
            ! /var/lib/apt/lists/partial
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/deploy-tts-space.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Set Environment Variables
        run: |
          echo "LOCAL_DIR=$REPO_ROOT/huggingface/spaces/openai-tts" >> $GITHUB_ENV

      - name: Print Environment Variables
        run: |
          echo "REPO_ROOT: $REPO_ROOT"
          echo "LOCAL_DIR: $LOCAL_DIR"
          echo "Current directory: $(pwd)"
          ls -la
          echo "Contents of LOCAL_DIR:"
          ls -la "$LOCAL_DIR"

      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.11"

      - name: Cache Python Dependencies
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('huggingface/spaces/openai-tts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Hugging Face CLI
        run: |
          pip install --upgrade pip
          pip install -U "huggingface_hub[cli,hf_transfer]"

      - name: Hugging Face Login
        run: huggingface-cli login --token "${{ secrets.HUGGINGFACE_TOKEN }}"

      - name: Upload to Remote
        run: |
          echo "Uploading files from $LOCAL_DIR to $REPO_ID at $REMOTE_DIR"
          huggingface-cli upload "$REPO_ID" "$LOCAL_DIR" "$REMOTE_DIR" --repo-type space
