name: Deploy HF TTS Space

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "huggingface/spaces/openai-tts/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HF_TRANSFER_ENABLED: "1"
      REPO_ID: ${{ secrets.REPO_ID }}
      REMOTE_DIR: "."
      REPO_ROOT: ${{ github.workspace }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          echo "LOCAL_DIR=$REPO_ROOT/huggingface/spaces/openai-tts" >> $GITHUB_ENV

      - name: Print Environment Variables
        run: |
          echo "REPO_ROOT: $REPO_ROOT"
          echo "LOCAL_DIR: $LOCAL_DIR"
          echo "Current directory: $(pwd)"
          ls -la
          echo "Contents of LOCAL_DIR:"
          ls -la "$LOCAL_DIR"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Hugging Face CLI
        run: |
          pip install --upgrade pip
          pip install -U "huggingface_hub[cli,hf_transfer]"

      - name: Hugging Face Login
        run: huggingface-cli login --token "${{ secrets.HUGGINGFACE_TOKEN }}"

      - name: Upload to Remote
        run: |
          echo "Uploading files from $LOCAL_DIR to $REPO_ID at $REMOTE_DIR"
          huggingface-cli upload "$REPO_ID" "$LOCAL_DIR" "$REMOTE_DIR" --repo-type space
