name: Deploy HF Space
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "huggingface/spaces/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HF_TRANSFER_ENABLED: "1"
      REPO_ID: ${{ secrets.REPO_ID }}
      REMOTE_DIR: "."
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "REPO_ROOT=$(git rev-parse --show-toplevel)" >> $GITHUB_ENV
          echo "LOCAL_DIR=$REPO_ROOT/huggingface/spaces/openai-tts" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Hugging Face CLI
        run: pip install -U "huggingface_hub[cli,hf_transfer]"

      - name: Hugging Face Login
        run: huggingface-cli login --token "${{ secrets.HUGGINGFACE_TOKEN }}"

      - name: Upload Space
        run: |
          echo "Uploading files from $LOCAL_DIR to $REPO_ID at $REMOTE_DIR"
          huggingface-cli upload "$REPO_ID" "$LOCAL_DIR" "$REMOTE_DIR" --repo-type space
