name: "Deploy Hugging Face Space: OpenAI TTS"

on:
  workflow_dispatch:
  push:
    paths:
      - 'huggingface/openai-tts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Inputs
        run: |
          set -e
          if [ -z "${{ secrets.HF_TOKEN }}" ]; then
            echo "Error: HF_TOKEN is not set."
            exit 1
          fi

      - name: Set Git Config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir huggingface_hub[cli,hf_transfer]

      - name: Login to Hugging Face
        run: huggingface-cli login --token "${{ secrets.HF_TOKEN }}"

      - name: Clone Hugging Face Space Repository
        run: |
          REPO_URL="https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/${{ secrets.HF_SPACE }}.git"
          GIT_LFS_SKIP_SMUDGE=1 git clone "$REPO_URL" space

      - name: Sync Files to Space Repository
        run: |
          rsync -av --delete ./huggingface/openai-tts/ ./space/

      - name: Commit and Push Changes
        working-directory: space
        run: |
          git add .
          git commit --allow-empty -m "Update deployment on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git push origin main
