name: Generate PDFs

on:
  push:
    paths:
      - ".github/workflows/generate-pdfs.yml"
      - "docs/design-document/Final_Project_Team_3_Deliverable_1.tex"
      - "docs/design-document/references.bib"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  REPO_NAME: aai540-group3/project
  EVENT_TYPE: create-release

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 1

      - name: Set up environment variables
        run: |
          echo "REPO_ROOT=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "DESIGN_DOC_DIR=$GITHUB_WORKSPACE/docs/design-document" >> $GITHUB_ENV
          echo "TEX_FILE=$GITHUB_WORKSPACE/docs/design-document/Final_Project_Team_3_Deliverable_1.tex" >> $GITHUB_ENV
          echo "BIB_FILE=$GITHUB_WORKSPACE/docs/design-document/references.bib" >> $GITHUB_ENV
          echo "PDF_FILE=$GITHUB_WORKSPACE/docs/design-document/Final_Project_Team_3_Deliverable_1.pdf" >> $GITHUB_ENV
          echo "ROOT_PDF_FILE=$GITHUB_WORKSPACE/Final_Project_Team_3_Deliverable_1.pdf" >> $GITHUB_ENV

      - name: Print Environment Variables
        run: |
          echo "REPO_ROOT: ${{ env.REPO_ROOT }}"
          echo "DESIGN_DOC_DIR: ${{ env.DESIGN_DOC_DIR }}"
          echo "TEX_FILE: ${{ env.TEX_FILE }}"
          echo "BIB_FILE: ${{ env.BIB_FILE }}"
          echo "PDF_FILE: ${{ env.PDF_FILE }}"
          echo "ROOT_PDF_FILE: ${{ env.ROOT_PDF_FILE }}"
          echo "Current directory: $(pwd)"
          ls -la
          echo "Checking file existence and permissions:"
          for file in "${{ env.TEX_FILE }}" "${{ env.BIB_FILE }}"; do
            if [ -f "$file" ]; then
              echo "$file exists. Permissions: $(ls -l "$file")"
            else
              echo "$file does not exist."
            fi
          done
          echo "Contents of DESIGN_DOC_DIR:"
          ls -la ${{ env.DESIGN_DOC_DIR }} || echo "DESIGN_DOC_DIR does not exist or is not accessible"

      - name: Cache Apt Packages
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('/etc/apt/sources.list') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install TeX and Tools
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            biber \
            texlive \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-bibtex-extra \
            texlive-science \
            texlive-extra-utils \
            poppler-utils

      - name: Remove Old PDFs
        run: |
          rm -f "$PDF_FILE"
          rm -f "$ROOT_PDF_FILE"

      - name: Generate PDFs
        run: |
          TEXINPUTS="$DESIGN_DOC_DIR:."
          pdflatex -interaction=nonstopmode -file-line-error -halt-on-error "$TEX_FILE"
          biber "$BIB_FILE"
          pdflatex -interaction=nonstopmode -file-line-error -halt-on-error "$TEX_FILE"
          pdflatex -interaction=nonstopmode -file-line-error -halt-on-error "$TEX_FILE"

      - name: Check for PDF
        run: |
          if [ ! -f "$PDF_FILE" ]; then
            echo "ERROR: PDF generation failed!"
            exit 1
          fi

      - name: Copy PDF to Top-Level Repo Diectory
        run: |
          cp "$PDF_FILE" "$ROOT_PDF_FILE"

      - name: Get Word Count
        run: |
          WORDS=$(texcount -1 -sum -inc "$TEX_FILE" | grep "Sum count:" | awk '{print $3}')
          echo "WORDS=$WORDS" >> $GITHUB_ENV

      - name: Get Page Count
        run: |
          PAGES=$(pdfinfo "$PDF_FILE" | grep Pages: | awk '{print $2}')
          echo "PAGES=$PAGES" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Push to Remote
        run: |
          git add "$ROOT_PDF_FILE"
          git commit -m "WORDS: $WORDS | PAGES: $PAGES"
          git pull origin main
          git push origin main

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.AAI540_GROUP3_DISPATCH_TOKEN }}
          repository: ${{ env.REPO_NAME }}
          event-type: ${{ env.EVENT_TYPE }}
