name: Generate Video
on:
  push:
    paths:
      - "Final_Project_Team_3_Deliverable_2.pptx"
      - "./.github/workflows/generate-video.yml"
      - "scripts/pptx2video.py"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  generate-video:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4.1.7
        with:
          ref: main
          fetch-depth: 1
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
              bc \
              ffmpeg \
              libreoffice \
              poppler-utils

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
              aiohttp \
              moviepy \
              numpy \
              openai \
              pdf2image \
              Pillow==6.2.2 \
              python-pptx \
              tenacity

      - name: Generate Video
        id: generate
        run: |
          python scripts/pptx2video.py Final_Project_Team_3_Deliverable_2.pptx
        continue-on-error: false

      - name: Check video creation
        id: check_video
        run: |
          if [ -f "Final_Project_Team_3_Deliverable_2.mp4" ]; then
            echo "video_created=true" >> $GITHUB_OUTPUT
          else
            echo "video_created=false" >> $GITHUB_OUTPUT
            echo "::error title=Video generation failed::Video file not found."
          fi

      - name: Get video duration
        id: duration
        if: steps.check_video.outputs.video_created == 'true'
        run: |
          duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 Final_Project_Team_3_Deliverable_2.mp4)
          minutes=$(printf "%.0f" $(echo "$duration/60" | bc))
          seconds=$(printf "%.0f" $(echo "$duration%60" | bc))
          echo "duration=${minutes}m ${seconds}s" >> $GITHUB_OUTPUT

      - name: Save assets
        if: steps.check_video.outputs.video_created == 'true'
        run: |
          mkdir -p video-assets
          cp Final_Project_Team_3_Deliverable_2.pdf video-assets/
          cp Final_Project_Team_3_Deliverable_2.mp4 video-assets/
          if [ -d "/tmp" ]; then
            find /tmp -name "slide_*.png" -exec cp {} video-assets/ \;
            find /tmp -name "voice_*.mp3" -exec cp {} video-assets/ \;
            find /tmp -name "video_*.mp4" -exec cp {} video-assets/ \;
          fi

      - name: Commit and push changes
        if: steps.check_video.outputs.video_created == 'true'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add Final_Project_Team_3_Deliverable_2.mp4 video-assets
          git commit -m "Updated video and assets - video duration: ${{ steps.duration.outputs.duration }}" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main

      - name: Check for failure
        if: steps.check_video.outputs.video_created == 'false'
        run: |
          echo "Video generation failed. Please check the logs for errors."
          exit 1
