name: Generate Video
on:
  push:
    paths:
      - "Final_Project_Team_3_Deliverable_2.pptx"
      - "./.github/workflows/generate-video.yml"
      - "scripts/pptx2video.py"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  generate-video:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4.1.7
        with:
          ref: main
          fetch-depth: 1
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
              bc \
              ffmpeg \
              libreoffice \
              poppler-utils \
              rsync

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
              aiohttp \
              moviepy \
              numpy \
              openai \
              pdf2image \
              Pillow \
              python-pptx \
              tenacity

      - name: Generate Video
        id: generate
        run: |
          python scripts/pptx2video.py Final_Project_Team_3_Deliverable_2.pptx
        continue-on-error: false

      - name: Check video creation
        id: check_video
        run: |
          if [ -f "Final_Project_Team_3_Deliverable_2.mp4" ]; then
            echo "video_created=true" >> $GITHUB_OUTPUT
          else
            echo "video_created=false" >> $GITHUB_OUTPUT
            echo "::error title=Video generation failed::Video file not found."
          fi

      - name: Get video duration
        id: duration
        if: steps.check_video.outputs.video_created == 'true'
        run: |
          duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 Final_Project_Team_3_Deliverable_2.mp4)
          minutes=$(printf "%.0f" $(echo "$duration/60" | bc))
          seconds=$(printf "%.0f" $(echo "$duration%60" | bc))
          echo "duration=${minutes}m ${seconds}s" >> $GITHUB_OUTPUT

      - name: Update assets
        if: steps.check_video.outputs.video_created == 'true'
        run: |
          # Ensure PDF and MP4 are in the top-level directory
          # (They should already be there from the video generation step)

          # Create a temporary directory for other assets
          mkdir -p temp_assets

          # Copy intermediate files if they exist
          # Use find with -readable to only process files we have permission to read
          find /tmp -readable -type f \( -name "slide_*.png" -o -name "voice_*.mp3" -o -name "video_*.mp4" \) -exec cp {} temp_assets/ \; 2>/dev/null || true

          # Use rsync to update video-assets directory
          # --delete option removes files in video-assets that don't exist in temp_assets
          mkdir -p video-assets
          rsync -av --delete temp_assets/ video-assets/

          # Clean up temporary directory
          rm -rf temp_assets

          # List contents of video-assets for verification
          echo "Contents of video-assets directory:"
          ls -la video-assets/
        shell: /usr/bin/bash -e {0}

      - name: Commit and push changes
        if: steps.check_video.outputs.video_created == 'true'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add Final_Project_Team_3_Deliverable_2.pdf Final_Project_Team_3_Deliverable_2.mp4 video-assets
          git commit -m "Updated video and assets - video duration: ${{ steps.duration.outputs.duration }}" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main

      - name: Check for failure
        if: steps.check_video.outputs.video_created == 'false'
        run: |
          echo "Video generation failed. Please check the logs for errors."
          exit 1
