name: MLOps Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "conf/**"
      - "dvc.yaml"
      - "params.yaml"
      - "dvc.lock"
      - "requirements.txt"
      - ".github/workflows/mlops-pipeline.yml"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "conf/**"
      - "dvc.yaml"
      - "params.yaml"
      - "dvc.lock"
      - "requirements.txt"
      - ".github/workflows/mlops-pipeline.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-mlops-pipeline:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DVC_STUDIO_TOKEN: ${{ secrets.DVC_STUDIO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Cache Python dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure DVC remotes
        run: |
          dvc remote modify models_remote region $AWS_DEFAULT_REGION
          dvc remote modify datasets_remote region $AWS_DEFAULT_REGION

      - name: Cache DVC cache directory
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .dvc/cache
          key: ${{ runner.os }}-dvc-cache-${{ hashFiles('dvc.lock') }}
          restore-keys: |
            ${{ runner.os }}-dvc-cache-

      - name: Pull data and models from DVC remotes
        run: |
          dvc pull

      - name: Run DVC pipeline
        run: |
          dvc exp run --run-all

      - name: Push data and models to DVC remotes
        if: always()
        run: |
          dvc push

      - name: Commit and push changes
        if: always()
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          commit_message: "Update DVC artifacts and metrics"
          branch: ${{ github.ref_name }}
          file_pattern: |
            dvc.lock
            dvclive/
            dvclive_evaluate/
            reports/metrics.json
