name: MLOps Pipeline

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/mlops-pipeline.yml"
      - "v/**"
      - "dvc.lock"
      - "dvc.yaml"
      - "params.yaml"
      - "requirements-pipeline.txt"
      - "src/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/mlops-pipeline.yml"
      - "configs/**"
      - "dvc.lock"
      - "dvc.yaml"
      - "params.yaml"
      - "requirements-pipeline.txt"
      - "src/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  run-mlops-pipeline:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DATASETS_REMOTE: ${{ secrets.DATASETS_REMOTE }}
      DVC_STUDIO_TOKEN: ${{ secrets.DVC_STUDIO_TOKEN }}
      MODELS_REMOTE: ${{ secrets.MODELS_REMOTE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.11"

      - name: Cache Python Dependencies
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-pipeline.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-pipeline.txt

      - uses: iterative/setup-cml@f12ea7685438c1fc438d50f77519b3860cf5fa98 # v2.0.1
      - uses: iterative/setup-dvc@2508d098217d24eef3c0e8d7bc0ce7b9ca0723c3 # v1.1.2

      - name: Configure DVC
        run: |
          dvc init
          dvc config core.autostage true
          dvc config hydra.enabled true
          dvc config studio.url https://studio.iterative.ai
          dvc remote add -f datasets_remote $DATASETS_REMOTE -d
          dvc remote add -f models_remote $MODELS_REMOTE
          dvc remote modify datasets_remote region $AWS_DEFAULT_REGION
          dvc remote modify models_remote region $AWS_DEFAULT_REGION
          dvc remote list

      - name: Cache DVC Directory
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: .dvc/cache
          key: ${{ runner.os }}-dvc-cache-${{ hashFiles('dvc.lock') }}
          restore-keys: |
            ${{ runner.os }}-dvc-cache-

      - name: Pull from DVC remotes
        run: dvc pull

      - name: Run DVC pipeline
        run: dvc repro

      - name: Push to DVC remotes
        if: always()
        run: dvc push

      - name: Push to Git Remote
        if: always()
        id: commit_and_push
        continue-on-error: true
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config pull.rebase false

          [ -f dvc.lock ] && git add dvc.lock
          [ -d dvclive ] && git add dvclive
          [ -d dvclive_evaluate ] && git add dvclive_evaluate
          [ -f reports/metrics.json ] && git add reports/metrics.json

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update DVC artifacts and metrics"
            git pull origin main
            git push origin main
          fi

      - name: Create Pull Request if push failed
        if: failure() && steps.commit_and_push.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config pull.rebase false

          NEW_BRANCH="auto/update-dvc-artifacts-${{ github.run_id }}"
          git checkout -b $NEW_BRANCH

          [ -f dvc.lock ] && git add dvc.lock
          [ -d dvclive ] && git add dvclive
          [ -d dvclive_evaluate ] && git add dvclive_evaluate
          [ -f reports/metrics.json ] && git add reports/metrics.json

          if git diff --staged --quiet; then
            echo "No changes to commit. Skipping PR creation."
          else
            git commit -m "Update DVC artifacts and metrics"
            git push origin $NEW_BRANCH

            gh pr create \
              --title "Update DVC artifacts and metrics" \
              --body "This PR updates the DVC artifacts and metrics." \
              --label "automated-pr" \
              --base ${{ github.ref_name }} \
              --head $NEW_BRANCH
          fi
