name: MLOps Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "conf/**"
      - "dvc.yaml"
      - "params.yaml"
      - "dvc.lock"
      - "requirements.txt"
      - ".github/workflows/mlops-pipeline.yml"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "conf/**"
      - "dvc.yaml"
      - "params.yaml"
      - "dvc.lock"
      - "requirements.txt"
      - ".github/workflows/mlops-pipeline.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-run-pipeline:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DVC_STUDIO_TOKEN: ${{ secrets.DVC_STUDIO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure DVC remotes
        run: |
          dvc remote modify models_remote region $AWS_DEFAULT_REGION
          dvc remote modify datasets_remote region $AWS_DEFAULT_REGION
        shell: bash

      - name: Pull data and models from DVC remotes
        run: |
          dvc pull --force

      - name: Run DVC pipeline
        run: |
          dvc exp run --queue

      - name: Push data and models to DVC remotes
        if: always()
        run: |
          dvc push

      - name: Apply queued experiments and push changes
        if: always()
        run: |
          dvc exp apply
          dvc push

      - name: Commit and push changes
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "Update DVC artifacts and metrics"
          branch: ${{ github.ref }}
          file_pattern: |
            dvc.lock
            dvclive/*
            reports/metrics.json
