name: Package Repository

on:
  push:
    branches:
      - main
    paths:
      - ".dvcignore"
      - ".env.template"
      - ".gitattributes"
      - ".github/workflows/mlops-pipeline.yml"
      - ".github/workflows/package-repo.yml"
      - ".gitignore"
      - "configs/**"
      - "dvc.lock"
      - "dvc.yaml"
      - "dvclive/**"
      - "LICENSE"
      - "notebooks/**"
      - "params.yaml"
      - "README.md"
      - "reports/**"
      - "requirements.txt"
      - "src/**"
      - "terraform/main.tf"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  package-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 1

      - name: Install System Dependencies
        run: sudo apt-get install -y pigz zip

      - name: Create File List
        run: |
          cat << EOF > files.txt
          .dvcignore
          .env.template
          .gitattributes
          .github/workflows/mlops-pipeline.yml
          .gitignore
          configs/
          dvc.lock
          dvc.yaml
          dvclive/
          LICENSE
          notebooks/
          params.yaml
          README.md
          reports/
          requirements.txt
          src/
          terraform/main.tf
          EOF

      - name: Zip Repository
        run: zip -r -0 $(cat files.txt) | pigz -9 > Final_Project_Team_3_Deliverable_3.zip

      - name: Check File Size
        run: ls -lh Final_Project_Team_3_Deliverable_3.zip

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config pull.rebase false

      - name: Push to Remote
        run: |
          git add Final_Project_Team_3_Deliverable_3.zip
          git commit -m "Update Final_Project_Team_3_Deliverable_3.zip"
          git pull origin main
          git push origin main

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.AAI540_GROUP3_DISPATCH_TOKEN }}
          repository: aai540-group3/project
          event-type: create-release

      - name: Cleanup
        if: always()
        run: rm -f files.txt
