name: Zip Repository

on:
  push:
    branches:
      - main
    paths:
      - ".dvcignore"
      - ".env.template"
      - ".gitattributes"
      - ".github/workflows/mlops-pipeline.yml"
      - ".github/workflows/zip-repository.yml"
      - ".gitignore"
      - "configs/**"
      - "dvc.lock"
      - "dvc.yaml"
      - "dvclive/**"
      - "LICENSE"
      - "notebooks/**"
      - "params.yaml"
      - "README.md"
      - "reports/**"
      - "requirements.txt"
      - "src/**"
      - "terraform/main.tf"
  workflow_dispatch:

jobs:
  zip-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pigz
        run: sudo apt-get install -y pigz

      - name: Create temporary directory
        run: mkdir -p temp_repo

      - name: Copy files to temporary directory
        run: |
          files=(
            ".dvcignore"
            ".env.template"
            ".gitattributes"
            ".github/workflows/mlops-pipeline.yml"
            ".gitignore"
            "configs"
            "dvc.lock"
            "dvc.yaml"
            "dvclive"
            "LICENSE"
            "notebooks"
            "params.yaml"
            "README.md"
            "reports"
            "requirements.txt"
            "src"
            "terraform/main.tf"
          )
          for file in "${files[@]}"; do
            if [[ -d "$file" ]]; then
              cp -r "$file" temp_repo/
            else
              cp "$file" temp_repo/
            fi
          done

      - name: Remove unwanted files
        run: |
          unwanted_files=(
            ".gitkeep"
            ".gitignore"
            ".gitattributes"
          )
          for file in "${unwanted_files[@]}"; do
            find temp_repo -type f -name "$file" -delete
          done

      - name: Zip repository
        run: zip -r -0 -9 temp_repo/ | pigz -9 > Final_Project_Team_3_Deliverable_3.zip

      - name: Cleanup
        run: rm -rf temp_repo

      - name: Check zip file size
        run: ls -lh Final_Project_Team_3_Deliverable_3.zip

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push zip file
        run: |
          git add Final_Project_Team_3_Deliverable_3.zip
          git commit -m "Update Final_Project_Team_3_Deliverable_3.zip"
          git pull
          git push

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.AAI540_GROUP3_DISPATCH_TOKEN }}
          repository: aai540-group3/project
          event-type: create-release
